package schema

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

/**
 * Generated by [jsonschema2pojo](https://www.jsonschema2pojo.org/) for QQ card messages which doesn't match any known pattern.
 */
class GroupCardFallbackMessage {
    @SerializedName("app")
    @Expose
    var app: String? = null

    @SerializedName("desc")
    @Expose
    var desc: String? = null

    @SerializedName("view")
    @Expose
    var view: String? = null

    @SerializedName("ver")
    @Expose
    var ver: String? = null

    @SerializedName("prompt")
    @Expose
    var prompt: String? = null

    @SerializedName("meta")
    @Expose
    var meta: Meta? = null

    @SerializedName("config")
    @Expose
    var config: Config? = null

    inner class Config
    inner class Meta
}