package schema

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

/**
 * Generated by [jsonschema2pojo](https://www.jsonschema2pojo.org/) for QQ JSON structured card messages.
 */
class GroupStructMessage {
    @SerializedName("app")
    @Expose
    var app: String? = null

    @SerializedName("desc")
    @Expose
    var desc: String? = null

    @SerializedName("view")
    @Expose
    var view: String? = null

    @SerializedName("ver")
    @Expose
    var ver: String? = null

    @SerializedName("prompt")
    @Expose
    var prompt: String? = null

    @SerializedName("meta")
    @Expose
    var meta: Meta? = null

    @SerializedName("config")
    @Expose
    var config: Config? = null

    inner class Config {
        @SerializedName("autosize")
        @Expose
        var autosize: Boolean? = null

        @SerializedName("ctime")
        @Expose
        var ctime: Int? = null

        @SerializedName("forward")
        @Expose
        var forward: Boolean? = null

        @SerializedName("token")
        @Expose
        var token: String? = null

        @SerializedName("type")
        @Expose
        var type: String? = null
    }

    inner class Meta {
        @SerializedName("news")
        @Expose
        var news: News? = null
    }

    inner class News {
        @SerializedName("action")
        @Expose
        var action: String? = null

        @SerializedName("android_pkg_name")
        @Expose
        var androidPkgName: String? = null

        @SerializedName("app_type")
        @Expose
        var appType: Int? = null

        @SerializedName("appid")
        @Expose
        var appid: Int? = null

        @SerializedName("ctime")
        @Expose
        var ctime: Int? = null

        @SerializedName("desc")
        @Expose
        var desc: String? = null

        @SerializedName("jumpUrl")
        @Expose
        var jumpUrl: String? = null

        @SerializedName("preview")
        @Expose
        var preview: String? = null

        @SerializedName("source_icon")
        @Expose
        var sourceIcon: String? = null

        @SerializedName("source_url")
        @Expose
        var sourceUrl: String? = null

        @SerializedName("tag")
        @Expose
        var tag: String? = null

        @SerializedName("title")
        @Expose
        var title: String? = null

        @SerializedName("uin")
        @Expose
        var uin: Int? = null
    }
}