package schema

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

/**
 * Generated by [jsonschema2pojo](https://www.jsonschema2pojo.org/) for QQ mini app messages.
 */
class GroupMiniAppMessage {
    @SerializedName("config")
    @Expose
    var config: Config? = null

    @SerializedName("prompt")
    @Expose
    var prompt: String? = null

    @SerializedName("app")
    @Expose
    var app: String? = null

    @SerializedName("ver")
    @Expose
    var ver: String? = null

    @SerializedName("appID")
    @Expose
    var appID: String? = null

    @SerializedName("view")
    @Expose
    var view: String? = null

    @SerializedName("meta")
    @Expose
    var meta: Meta? = null

    @SerializedName("bthirdappforward")
    @Expose
    var bthirdappforward: Boolean? = null

    @SerializedName("bthirdappforwardforbackendswitch")
    @Expose
    var bthirdappforwardforbackendswitch: Boolean? = null

    @SerializedName("desc")
    @Expose
    var desc: String? = null

    inner class Config {
        @SerializedName("height")
        @Expose
        var height: Int? = null

        @SerializedName("forward")
        @Expose
        var forward: Int? = null

        @SerializedName("ctime")
        @Expose
        var ctime: Int? = null

        @SerializedName("width")
        @Expose
        var width: Int? = null

        @SerializedName("type")
        @Expose
        var type: String? = null

        @SerializedName("token")
        @Expose
        var token: String? = null

        @SerializedName("autoSize")
        @Expose
        var autoSize: Int? = null
    }

    inner class Detail1 {
        @SerializedName("appid")
        @Expose
        var appid: String? = null

        @SerializedName("preview")
        @Expose
        var preview: String? = null

        @SerializedName("shareTemplateData")
        @Expose
        var shareTemplateData: ShareTemplateData? = null

        @SerializedName("gamePointsUrl")
        @Expose
        var gamePointsUrl: String? = null

        @SerializedName("gamePoints")
        @Expose
        var gamePoints: String? = null

        @SerializedName("url")
        @Expose
        var url: String? = null

        @SerializedName("appType")
        @Expose
        var appType: Int? = null

        @SerializedName("desc")
        @Expose
        var desc: String? = null

        @SerializedName("title")
        @Expose
        var title: String? = null

        @SerializedName("scene")
        @Expose
        var scene: Int? = null

        @SerializedName("host")
        @Expose
        var host: Host? = null

        @SerializedName("icon")
        @Expose
        var icon: String? = null

        @SerializedName("shareTemplateId")
        @Expose
        var shareTemplateId: String? = null

        @SerializedName("qqdocurl")
        @Expose
        var qqdocurl: String? = null

        @SerializedName("showLittleTail")
        @Expose
        var showLittleTail: String? = null
    }

    inner class Host {
        @SerializedName("uin")
        @Expose
        var uin: Int? = null

        @SerializedName("nick")
        @Expose
        var nick: String? = null
    }

    inner class Meta {
        @SerializedName("detail_1")
        @Expose
        var detail1: Detail1? = null
    }

    inner class ShareTemplateData
}