package schema

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

/**
 * Generated by [jsonschema2pojo](https://www.jsonschema2pojo.org/) for QQ announcements.
 */
class GroupAnnounceMessage {
    @SerializedName("app")
    @Expose
    var app: String? = null

    @SerializedName("config")
    @Expose
    var config: Config? = null

    @SerializedName("desc")
    @Expose
    var desc: String? = null

    @SerializedName("extra")
    @Expose
    var extra: Extra? = null

    @SerializedName("meta")
    @Expose
    var meta: Meta? = null

    @SerializedName("prompt")
    @Expose
    var prompt: String? = null

    @SerializedName("ver")
    @Expose
    var ver: String? = null

    @SerializedName("view")
    @Expose
    var view: String? = null

    inner class Mannounce {
        @SerializedName("cr")
        @Expose
        var cr: Int? = null

        @SerializedName("encode")
        @Expose
        var encode: Int? = null

        @SerializedName("fid")
        @Expose
        var fid: String? = null

        @SerializedName("gc")
        @Expose
        var gc: String? = null

        @SerializedName("sign")
        @Expose
        var sign: String? = null

        @SerializedName("text")
        @Expose
        var text: String? = null

        @SerializedName("title")
        @Expose
        var title: String? = null

        @SerializedName("tw")
        @Expose
        var tw: Int? = null

        @SerializedName("uin")
        @Expose
        var uin: String? = null
    }

    inner class Meta {
        @SerializedName("mannounce")
        @Expose
        var mannounce: Mannounce? = null
    }

    inner class Config {
        @SerializedName("ctime")
        @Expose
        var ctime: Int? = null

        @SerializedName("forward")
        @Expose
        var forward: Int? = null

        @SerializedName("token")
        @Expose
        var token: String? = null
    }

    inner class Extra {
        @SerializedName("app_type")
        @Expose
        var appType: Int? = null

        @SerializedName("appid")
        @Expose
        var appid: Int? = null

        @SerializedName("uin")
        @Expose
        var uin: Int? = null
    }
}