package schema

/**
 * Generated by [json2csharp](https://json2csharp.com/xml-to-java/) for QQ XML card messages.
 */
class GroupXMLMessage {
    class picture {
        var cover: String? = null
        var w = 0
        var h = 0
    }

    class item {
        var picture: picture? = null
        var title: String? = null
        var summary: String? = null
        var layout = 0
        var advertiser_id = 0
        var aid = 0
        var text: String? = null
    }

    class source {
        var name: String? = null
        var icon: String? = null
        var url: String? = null
        var action: String? = null
        var a_actionData: String? = null
        var appid = 0
    }

    class msg {
        var item: item? = null
        var source: source? = null
        var serviceID = 0
        var templateID = 0
        var action: String? = null
        var brief: String? = null
        var sourceMsgId = 0
        var url: String? = null
        var flag = 0
        var adverSign = 0
        var multiMsgFlag = 0
        var text: String? = null
    }
}